### ISSUE TITLE
Should we consider extending the `BroadwaySQS.SQSClient` behaviour?

### ISSUE THREAD

**Issue by dokie** [plataformatec/broadway_sqs#10]
As I mentioned in #9, I would like to extend the SQS visibility timeout dynamically at runtime which is possible through the underlying `ExAws.SQS` module. There are many ways it could be done but I wanted to know if you thought it would be an acceptable proposal to extend the `Broadway.SQSClient` behaviour in such a manner as;

```elixir
@type message_visibility :: {receipt_handle :: String.t(), visibility_timeout :: pos_integer()}
@type message_visibility_batch_entry :: {unique_id :: String.t(), visibility :: message_visibility()}
@type message_visibility_batch :: [message_visibility_batch_entry()]

@callback change_message_visibility(queue_name :: String.t(), visibility :: message_visibility()) :: {:ok, response :: map()} | {:error, details :: map()}
@callback change_message_visibility_batch(queue_name :: String.t(), batch :: message_visibility_batch()) :: {:ok, response :: map()} | {:error, details :: map()}
```

Or do you consider this to be too specific? Ideas welcomed of course.

**Comment by josevalim** [comment]
I think what we could do is to expose an API like this:

    BroadwaySQS.receipt(%Broadway.Message{}) :: {:ok, receipt} | {:error, :incompatible_producer}

This way you can get the receipt any time you want and do what you want with it.

**Comment by dokie** [comment]
@josevalim That would work fine too - it would allow what I require for sure. It _may_ open up the situation where the recipient stupidly or deliberately `deletes` the message from the queue ahead of the `Acknowledger`!

**Comment by josevalim** [comment]
@dokie if they want to do stupid stuff, they can do it anyway by accessing the receipt directly. So I am not worried. And we can add the proper disclaimer in the docs! :D

**Comment by dokie** [comment]
Fair point @josevalim 😉

**Comment by josevalim** [comment]
@dokie let's hear from @msaraiva and, if he agrees, would you be so kind to send a pull request?

**Comment by dokie** [comment]
Of course, it would be my pleasure to help out.

**Comment by msaraiva** [comment]
Ok, here's the suggestion:

  1. A new callback `message_receipt/1` or just `receipt/1` in `BroadwaySQS.SQSClient`
  2. Implement the new callback in `BroadwaySQS.ExAwsClient`
  3. Add a new public function `message_receipt/1` or just `receipt/1` to `BroadwaySQS.Producer` that extracts the client from the `acknowledger` fields and calls `client.message_receipt/1'

Would that be enough?

**Comment by josevalim** [comment]
Sounds perfect to me.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by dokie** [comment]
Great. I'll take this then now and work on it.
