### ISSUE TITLE
Is it possible to use profile as authentication method?

### ISSUE THREAD

**Issue by felipevolpone** [plataformatec/broadway_sqs#15]
Hi guys,

first of all, thanks for this project. I'm looking forward to test in an environment to consume around 1.5 million SQS messages per day.

I have been playing with it, but I didn't find a way to authenticate my app using AWS profile (like `~/.aws/config, [1]). If it's not possible, but you think that it would be nice to have it in the project, I'm wiling to send a PR.

[1] search for `Setting an Alternate Credentials Profile` in https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

**Comment by josevalim** [comment]
Yes, please see here: https://hexdocs.pm/ex_aws/ExAws.html#module-aws-key-configuration

You can pass those under config option when setting up your Broadway producer:

```elixir
      Broadway.start_link(MyBroadway,
        name: MyBroadway,
        producers: [
          default: [
            module: {BroadwaySQS.Producer,
              queue_name: "my_queue",
              config: [
                access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
                secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, {:awscli, "default", 30}, :instance_role]
              ]
            }
          ]
        ]
      )
```
