### ISSUE TITLE
Option to not hit live AWS when testing

### ISSUE THREAD

**Issue by churcho** [plataformatec/broadway_sqs#25]
I already have an `AWSMock` which I use in several places in my codebase. When testing BroadwaySQS, `BroadwaySQS.ExAwsClient` is used for calls and by that the app uses `ExAws.request`, is there a way to override this so I can use my mock in this setup?

**Comment by josevalim** [comment]
Hi @churcho! Broadway master has a dummy producer, which you would use in your test environment so you don't hit AWS.

**Comment by churcho** [comment]
Hi, I tried that option but now I am getting
```
{:shutdown, {:failed_to_start_child, HelloApi.Broadway.Consumer.Producer_sqs_1, {:undef, [{Broadway.DummyProducer, :init, [[queue_name: "api-test.fifo"]], []}, {Broadway.Producer, :init, 1, [file: 'lib/broadway/producer.ex', line: 40]},
```

**Comment by churcho** [comment]
Got it to work by changing deps to:
```
{:broadway, "~> 0.3.0", github: "plataformatec/broadway", override: true},
{:broadway_sqs, "~> 0.2.0"},
```

Basically replicated the structure [here](https://github.com/hexpm/hexdocs/blob/bbabd92712fe59aa0cce55236d44501669dc1a52/lib/hexdocs/queue.ex)
