### ISSUE TITLE
which Function for delete message from queue

### ISSUE THREAD

**Issue by ramudu63** [plataformatec/broadway_sqs#26]
I am using standard sqs, this won't delete the message after reading the message from the queue. In broadwat_sqs how I will delete message manually from the queue.

**Comment by josevalim** [comment]
Can you provide more information? What do you mean by standard sqs? Does it mean an ACK does not delete the message?

In any case, if you want to delete the message manually, you can use ExAWS.

**Comment by ramudu63** [comment]
I am using a standard queue, yes ack does not delete the message from queue after reading it.

**Comment by josevalim** [comment]
So checkout the ExAWS package and it should provide an API to delete messages. In case it doesn't, you can always perform a request to ExAWS HTTP endpoints directly.
