### ISSUE TITLE
Upgrade broadway dependency to version 0.4.0

### ISSUE THREAD

**Issue by bannmoore** [plataformatec/broadway_sqs#28]
Hello! 👋 We're currently in a situation where we're using `broadway_sqs` `0.2.0`, which is currently pulling in `broadway 0.3.0`. We're interested in leveraging [testing features](https://hexdocs.pm/broadway/Broadway.html#module-testing) that were introduced in `0.4.0`, such as `Broadway.DummyProducer`. 

For the moment we've recreated that producer in our project, but it'd be awesome if we could use Broadway `0.4.0` alongside `broadway_sqs`.

EDIT: I created [a PR](https://github.com/plataformatec/broadway_sqs/pull/29) for this!

```
$ mix deps.get
Resolving Hex dependencies...

Failed to use "broadway" (version 0.4.0) because
  apps/manifold/mix.exs requires ~> 0.4.0
  broadway_sqs (version 0.2.0) requires ~> 0.3.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

**Comment by josevalim** [comment]
v0.3.0 is out!
