### ISSUE TITLE
Example app broken

### ISSUE THREAD

**Issue by brian-petersen** [plataformatec/broadway_sqs#34]
With the upgrade to `ex_aws_sqs` from `2.x` to `3.x`, the example app is broken. Only the queue name is given, not the queue url as required now.

**Comment by josevalim** [comment]
Oh, good catch! We upgraded everything except the example app. Can you
please send a PR?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by msaraiva** [comment]
Closed by https://github.com/plataformatec/broadway_sqs/pull/38
