### ISSUE TITLE
More explicit docs on SQS message acknowledgment?

### ISSUE THREAD

**Issue by nocivus** [plataformatec/broadway_sqs#36]
Hey guys, great work on both Broadway and BSQS!

I was reading the documentation and it was not immediately obvious to me how the messages get acknowledged (or not) back to AWS in the handle_batch function.

Am i correct to assume that any messages that are returned as the return value get acknowledged and those who are not do not? If so, i think the phrasing on the docs could reflect this a bit better for newcomers. If not, do i have to somehow change the message to make sure it doesn't get acknowledged when i fail to process it?

Thanks in advance!
Pedro

**Comment by josevalim** [comment]
`handle_batch` should always return all messages it receives, I will update the docs to make this clear. For changing the ack behaviour on failure, see #17.

**Comment by nocivus** [comment]
Hey Jose, thanks for the quick answer. But you got me event more confused now :)

Say i am processing a batch of 10 messages but i don't like message number 9 for some reason and don't want to ack that one (i.e. want it to go to the error queue after the redrive policy count is reached). How do i proceed in that case? Still return the 10 messages in handle_batch but modify the one that i want failed in some way?

Thanks again!

**Comment by nocivus** [comment]
Ok, my bad. I should mark it as failed: https://hexdocs.pm/broadway/Broadway.Message.html#failed/2

**Comment by josevalim** [comment]
Np! I have added a warning if you happen to return less messages too.
