### ISSUE TITLE
`queue_url` & region config

### ISSUE THREAD

**Issue by sdomino** [plataformatec/broadway_sqs#37]
I have the following module configured:
```elixir
module:
  {BroadwaySQS.Producer,
    queue_url: "https://us-east-2.queue.amazonaws.com/100000000001/some_queue"
  }
```

When I start the application, Broadway starts polling against a queue region based on its own `config: region:` value or the `ex_aws: region:` config value (default: `us-east-1`):

`[debug] ExAws: Request URL: "https://sqs.us-east-1.amazonaws.com/"`

If I change the module config to the following (or the `ex_aws: region:` value):
```elixir
{BroadwaySQS.Producer,
  queue_url: "https://us-east-2.queue.amazonaws.com/100000000001/some_queue",
  config: [
    region: "us-west-1"
  ]}
```

It polls the following queue:

`[debug] ExAws: Request URL: "https://sqs.us-west-1.amazonaws.com/"`

#### Is it possible to poll a queue from a different region than what is configured as the `region` (strictly based on the `queue_url`)?

I'm not understanding the purpose of providing the [full queue url](https://hexdocs.pm/broadway_sqs/BroadwaySQS.Producer.html#module-options-for-broadwaysqs-exawsclient) (required) if it's just going to use the region from the `region` setting. Thanks!

**Comment by sdomino** [comment]
After thinking about it a bit more, I'm wondering if this might just be a leftover function of previous versions when you needed to specify the queue name. In that case, you would need to know the region.

**Comment by josevalim** [comment]
Yeah, looks like a left over. Is it mentioned in the docs? If so, can you send a PR remove any reference?
