### ISSUE TITLE
handle_failed does not ack messages

### ISSUE THREAD

**Issue by jnatherley** [plataformatec/broadway_sqs#43]
Hey,

Thank you so much for the work and effort you've put into this package. It's really a breeze. I think i discovered an issue with the current `:broadway_sqs ~> "0.5.0"`. According to the main documentation in broadway:

> This callback must return the same messages given to it, possibly updated. For example, you could update the message data or use Broadway.Message.configure_ack/2 in a centralized place to configure how to ack the message based on the failure reason.

According to the code inside `broadway_sqs/lib/broadway_sqs/ex_aws_client.ex`:
```
  @impl true
  def ack(ack_ref, successful, _failed) do
    successful
    |> Enum.chunk_every(@max_num_messages_allowed_by_aws)
    |> Enum.each(fn messages -> delete_messages(messages, ack_ref) end)
  end
```

`_failed` is never used and the messages just remain in the queue. In the end i wrote this, just to clean up:

```
  defp get_ack_ref({_, ack_ref, _}) do
    ack_ref
  end

  def handle_failed(messages, context) do
    message = List.first(messages)
    message.acknowledger
    |> get_ack_ref()
    |> BroadwaySQS.ExAwsClient.ack(messages, [])

    messages
  end
```
I've seen you're discussing it and perhaps it wasn't implemented yet, but just incase anyone else comes across this or there is something i'm missing.

Thanks again!

**Comment by josevalim** [comment]
Thanks for the report! We will close this in favor of #17. PRs are welcome.
